import React, { useEffect, useState } from "react";
import api from "../../services/api";
import Loader from "../../components/common/Loader";
import QuizView from "../../components/quiz/QuizView";

export default function AssignedQuizzes() {
  const [assignments, setAssignments] = useState([]);
  const [active, setActive] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    api.get("/faculty/assignments/public/list").then((r) => setAssignments(r.data));
  }, []);

  async function open(id) {
    setError("");
    setLoading(true);
    try {
      const { data } = await api.get(`/faculty/assignments/${id}/attempt`);
      setActive(data);
    } catch (err) {
      setError(err.response?.data?.error || "Couldn't load that assignment.");
    } finally {
      setLoading(false);
    }
  }

  if (active) {
    return (
      <div className="max-w-4xl mx-auto px-6 py-10">
        <button onClick={() => setActive(null)} className="text-glow text-sm hover:underline mb-4">
          ← Back to assignments
        </button>
        <h1 className="font-display text-3xl mb-1">{active.title}</h1>
        <p className="text-ink2 mb-6">{active.subject} · {active.difficulty}</p>
        <QuizView
          questions={active.quizContent.questions}
          topic={active.subject}
          difficulty={active.difficulty}
          assignmentId={active.id}
        />
      </div>
    );
  }

  return (
    <div className="max-w-3xl mx-auto px-6 py-10">
      <h1 className="font-display text-3xl mb-1">Assigned Quizzes</h1>
      <p className="text-ink2 mb-6">Quizzes your faculty has assigned, generated by Goose.</p>

      {error && <p className="text-coral text-sm mb-4">{error}</p>}
      {loading && <Loader />}

      {assignments.length === 0 ? (
        <p className="text-ink2 bg-panel rounded-2xl p-6">No assignments yet — check back later.</p>
      ) : (
        <div className="space-y-2">
          {assignments.map((a) => (
            <button
              key={a.id}
              onClick={() => open(a.id)}
              className="w-full text-left bg-panel hover:bg-panelLight transition rounded-xl px-5 py-3 flex items-center justify-between"
            >
              <div>
                <span className="font-medium">{a.title}</span>
                <span className="text-ink2 text-sm ml-2">· {a.subject} · {a.difficulty}</span>
              </div>
              {a.dueDate && <span className="text-ink2 text-xs">Due {new Date(a.dueDate).toLocaleDateString()}</span>}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}
